### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by R-romero** [R-romero/web-cv#1]
# HTML
- [x] Page skeleton
- [x] Semantic Tags
- [x] Static Content

# CSS
### Preparation
- [x] Establish Color Pallet
- [x] Font Picking
- [x] Prepare Icons
### Execution
- [x] Position Sections
##### Styling
- [x] Header
- [ ] About Me
- [x] Education
- [x] Portfolio
- [x] Contact Me
##### Animate
- [ ] Animations

# Responsive Design
Mobile first approach
- [ ] Tablet
- [ ] Mid-size screen
- [ ] Desktops
- [ ] 4k

# Javascript
- [ ] Develop an API to receive Dynamic Content

# React
- [ ] Re-write the whole thing using React :)
